spring:
  main:
    banner-mode: off
  sql:
    init:
      mode: always
      platform: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: my_user
    password: my_password
    driverClassName: org.postgresql.Driver