# Generated by Django 4.1.5 on 2023-01-20 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('route_long_name', models.CharField(blank=True, max_length=255, null=True)),
                ('route_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('route_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=255)),
                ('stop_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('stop_lat', models.DecimalField(decimal_places=13, max_digits=15)),
                ('stop_lon', models.DecimalField(decimal_places=13, max_digits=15)),
                ('parent_station', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('trip_headsign', models.CharField(blank=True, max_length=255, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.IntegerField()),
                ('min_transfer_time', models.IntegerField(blank=True, null=True)),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_stop', to='core.stop')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_stop', to='core.stop')),
            ],
        ),
        migrations.CreateModel(
            name='FootPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_duration', models.IntegerField(blank=True, null=True)),
                ('transfer_arr_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_arr_stop', to='core.stop')),
                ('transfer_dep_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_dep_stop', to='core.stop')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_time', models.IntegerField()),
                ('arr_time', models.IntegerField()),
                ('mode_transport', models.CharField(blank=True, max_length=255, null=True)),
                ('arr_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arr_stop', to='core.stop')),
                ('dep_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_stop', to='core.stop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trip')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.IntegerField()),
                ('departure_time', models.IntegerField()),
                ('stop_sequence', models.IntegerField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trip')),
            ],
            options={
                'unique_together': {('trip', 'stop_sequence')},
            },
        ),
    ]
